'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ChevronRight, Flame, Sparkles, AlertCircle } from 'lucide-react';
import AnimeCard, { Anime } from '../components/AnimeCard';
import AnimeSearch from '../components/AnimeSearch';
import AuthNav from '../components/AuthNav';

export default function Home(){
 const [latest,setLatest]=useState<Anime[]>([]),[upcoming,setUpcoming]=useState<Anime[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updated,setUpdated]=useState(''),[source,setSource]=useState('');
 const [menuOpen,setMenuOpen]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/anime?section=latest&page=1&limit=8',{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error);setLatest(data.data||[]);const u=await fetch('/api/anime?section=upcoming&page=1&limit=8',{cache:'no-store'});const upcomingData=await u.json();setUpcoming(upcomingData.data||[]);setUpdated(data.updatedAt||'');setSource(data.source||'Anime databases')}catch(e){setError(e instanceof Error?e.message:'Unable to load anime data.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const total=latest.length+upcoming.length;
 const closeMenu=()=>setMenuOpen(false);
 return <main>
  <nav className="siteNav"><Link className="brand" href="/" onClick={closeMenu}><span className="logo"><Sparkles size={18}/></span><b>AniPulse</b></Link><div className="navlinks"><Link href="/" className="active">Home</Link><Link href="/latest">Latest</Link><Link href="/upcoming">Upcoming</Link><Link href="/about" onClick={closeMenu}>About</Link></div><div className="desktopSearch"><AnimeSearch /></div><AuthNav /><button type="button" className={`mobileMenuButton${menuOpen?' isOpen':''}`} aria-label={menuOpen?'Close navigation':'Open navigation'} aria-expanded={menuOpen} aria-controls="mobile-navigation" onClick={()=>setMenuOpen(v=>!v)}><span className="swordIcon" aria-hidden="true"><span className="sword swordOne"><i className="blade"/><i className="guard"/><i className="grip"/><i className="pommel"/></span><span className="sword swordTwo"><i className="blade"/><i className="guard"/><i className="grip"/><i className="pommel"/></span></span></button>{menuOpen&&<div id="mobile-navigation" className="mobileNav"><div className="mobileSearch"><AnimeSearch compact /></div><Link href="/" onClick={closeMenu}><span>Home</span><ChevronRight size={15}/></Link><Link href="/latest" onClick={closeMenu}><span>Latest anime</span><ChevronRight size={15}/></Link><Link href="/upcoming" onClick={closeMenu}><span>Upcoming releases</span><ChevronRight size={15}/></Link><Link href="/about" onClick={closeMenu}><span>About</span><ChevronRight size={15}/></Link><div className="mobileAuth"><AuthNav /></div></div>}</nav>
  <section id="top" className="hero"><div className="heroGlow"/><div className="heroCopy"><div className="eyebrow"><Flame size={14}/> LIVE ANIME RADAR</div><h1>Your next<br/><em>favorite anime.</em></h1><p>Discover what is airing now and what is coming next, with real titles, artwork, release dates and synopses pulled from public anime databases.</p><div className="heroActions"><Link className="primary" href="/latest">Explore latest <ChevronRight size={17}/></Link><span><span className="liveDot"/> {source || 'Connecting to anime databases…'}</span></div></div><div className="heroPanel"><div className="panelTop"><span>DATABASE STATUS</span><span className="online"><i/> {loading?'SYNCING':'ONLINE'}</span></div><div className="bigNumber">{total || (loading?'…':'0')}</div><p>anime currently surfaced across this season and the upcoming slate.</p><div className="miniStats"><div><b>{latest.length}</b><span>airing now</span></div><div><b>{upcoming.length}</b><span>coming soon</span></div></div></div></section>
  <section id="latest" className="section"><div className="sectionHead"><div><span className="kicker">ON AIR NOW</span><h2>Latest anime</h2><p>Highlights from the current season.</p></div><Link className="textLink" href="/latest">View all <ChevronRight size={16}/></Link></div>{error&&<div className="error"><AlertCircle size={18}/><span>{error}</span><button onClick={load}>Try again</button></div>}{loading?<div className="skeletonGrid">{Array.from({length:8}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:latest.length?<div className="grid">{latest.map(a=><AnimeCard key={a.routeId||a.id} anime={a}/>)}</div>:<div className="empty">No latest anime available right now.</div>}</section>
  <section id="upcoming" className="section upcoming"><div className="sectionHead"><div><span className="kicker">COMING SOON</span><h2>Upcoming releases</h2><p>Future anime with announced release dates.</p></div><Link className="textLink" href="/upcoming">Browse all <ChevronRight size={16}/></Link></div>{loading?<div className="skeletonGrid">{Array.from({length:8}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:upcoming.length?<div className="grid">{upcoming.map(a=><AnimeCard key={a.routeId||a.id} anime={a}/>)}</div>:<div className="empty">No upcoming anime available right now.</div>}</section>
  <section id="how" className="info"><div><span className="kicker">ABOUT THE DATA</span><h2>Real anime data, not placeholders.</h2><p>AniPulse uses multiple public anime databases. AniList is the primary source, with Jikan / MyAnimeList and Kitsu available as fallbacks. Each anime also has its own overview page with a longer synopsis and detailed release information.</p></div><div className="sourceBox"><span>ACTIVE DATA SOURCE</span><b>{source || 'Connecting…'}</b><small>Public APIs · No API key required</small>{updated&&<small>Last synced · {new Date(updated).toLocaleTimeString()}</small>}</div></section>
  <footer><div className="brand"><span className="logo"><Sparkles size={16}/></span><b>AniPulse</b></div><span>AniList · Jikan / MyAnimeList · Kitsu</span></footer>
  <style jsx global>{`@media(max-width:800px){.swordIcon{position:relative;width:34px;height:34px;display:block;transform:none!important}.sword{position:absolute;left:0;top:0;width:34px;height:34px;display:block;transform-origin:17px 17px;transition:transform .62s cubic-bezier(.22,1,.36,1),filter .35s ease}.swordOne{transform:translateY(-7px)}.swordTwo{transform:translateY(7px) rotate(180deg)}.sword .blade{position:absolute;left:3px;top:15px;width:22px;height:4px;border-radius:1px 5px 5px 1px;background:linear-gradient(180deg,#fff 0%,#dce2df 35%,#737d78 60%,#f3f5f4 100%);box-shadow:0 1px 2px #000,0 0 4px rgba(255,255,255,.16)}.sword .blade:before{content:"";position:absolute;left:-2px;top:-4px;width:22px;height:12px;background:linear-gradient(135deg,#fff,#c8cfcb 48%,#68716c);clip-path:polygon(0 50%,76% 0,100% 50%,76% 100%);filter:drop-shadow(0 1px 1px #000)}.sword .guard{position:absolute;left:23px;top:10px;width:3px;height:14px;border-radius:2px;background:linear-gradient(90deg,#d8ffac,#719a42,#cfff9c);box-shadow:0 0 5px rgba(184,255,100,.3)}.sword .grip{position:absolute;left:26px;top:15px;width:7px;height:4px;border-radius:2px;background:repeating-linear-gradient(135deg,#303631 0 2px,#89928c 2px 3px);box-shadow:0 1px 2px #000}.sword .pommel{position:absolute;left:31px;top:14px;width:4px;height:6px;border-radius:50%;background:linear-gradient(135deg,#d9ffad,#6d913e);box-shadow:0 0 4px rgba(184,255,100,.25)}.mobileMenuButton[aria-expanded=true] .swordOne{transform:translate(-3px,2px) rotate(45deg)}.mobileMenuButton[aria-expanded=true] .swordTwo{transform:translate(3px,2px) rotate(135deg)}.mobileMenuButton[aria-expanded=true] .sword{filter:drop-shadow(0 0 5px rgba(184,255,100,.35))}.mobileMenuButton[aria-expanded=true] .swordOne .blade,.mobileMenuButton[aria-expanded=true] .swordTwo .blade{box-shadow:0 1px 2px #000,0 0 7px rgba(255,255,255,.22)}`}</style>
 </main>
}
