'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ChevronRight, Flame, Sparkles, AlertCircle, Menu, X } from 'lucide-react';
import AnimeCard, { Anime } from '../components/AnimeCard';
import AnimeSearch from '../components/AnimeSearch';
import AuthNav from '../components/AuthNav';

export default function Home(){
 const [latest,setLatest]=useState<Anime[]>([]),[upcoming,setUpcoming]=useState<Anime[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updated,setUpdated]=useState(''),[source,setSource]=useState('');
 const [menuOpen,setMenuOpen]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/anime?section=latest&page=1&limit=8',{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error);setLatest(data.data||[]);const u=await fetch('/api/anime?section=upcoming&page=1&limit=8',{cache:'no-store'});const upcomingData=await u.json();setUpcoming(upcomingData.data||[]);setUpdated(data.updatedAt||'');setSource(data.source||'Anime databases')}catch(e){setError(e instanceof Error?e.message:'Unable to load anime data.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const total=latest.length+upcoming.length;
 const closeMenu=()=>setMenuOpen(false);
 return <main>
  <nav className="siteNav"><Link className="brand" href="/" onClick={closeMenu}><span className="logo"><Sparkles size={18}/></span><b>AniPulse</b></Link><div className="navlinks"><Link href="/" className="active">Home</Link><Link href="/latest">Latest</Link><Link href="/upcoming">Upcoming</Link><Link href="#how" onClick={closeMenu}>About</Link></div><AnimeSearch /><AuthNav /><button className="mobileMenuButton" aria-label={menuOpen?'Close navigation':'Open navigation'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X size={20}/>:<Menu size={20}/>}</button>{menuOpen&&<div className="mobileNav"><Link href="/" onClick={closeMenu}>Home</Link><Link href="/latest" onClick={closeMenu}>Latest anime</Link><Link href="/upcoming" onClick={closeMenu}>Upcoming releases</Link><Link href="#how" onClick={closeMenu}>About</Link><AuthNav /></div>}</nav>
  <section id="top" className="hero"><div className="heroGlow"/><div className="heroCopy"><div className="eyebrow"><Flame size={14}/> LIVE ANIME RADAR</div><h1>Your next<br/><em>favorite anime.</em></h1><p>Discover what is airing now and what is coming next, with real titles, artwork, release dates and synopses pulled from public anime databases.</p><div className="heroActions"><Link className="primary" href="/latest">Explore latest <ChevronRight size={17}/></Link><span><span className="liveDot"/> {source || 'Connecting to anime databases…'}</span></div></div><div className="heroPanel"><div className="panelTop"><span>DATABASE STATUS</span><span className="online"><i/> {loading?'SYNCING':'ONLINE'}</span></div><div className="bigNumber">{total || (loading?'…':'0')}</div><p>anime currently surfaced across this season and the upcoming slate.</p><div className="miniStats"><div><b>{latest.length}</b><span>airing now</span></div><div><b>{upcoming.length}</b><span>coming soon</span></div></div></div></section>
  <section id="latest" className="section"><div className="sectionHead"><div><span className="kicker">ON AIR NOW</span><h2>Latest anime</h2><p>Highlights from the current season.</p></div><Link className="textLink" href="/latest">View all <ChevronRight size={16}/></Link></div>{error&&<div className="error"><AlertCircle size={18}/><span>{error}</span><button onClick={load}>Try again</button></div>}{loading?<div className="skeletonGrid">{Array.from({length:8}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:latest.length?<div className="grid">{latest.map(a=><AnimeCard key={a.routeId||a.id} anime={a}/>)}</div>:<div className="empty">No latest anime available right now.</div>}</section>
  <section id="upcoming" className="section upcoming"><div className="sectionHead"><div><span className="kicker">COMING SOON</span><h2>Upcoming releases</h2><p>Future anime with announced release dates.</p></div><Link className="textLink" href="/upcoming">Browse all <ChevronRight size={16}/></Link></div>{loading?<div className="skeletonGrid">{Array.from({length:8}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:upcoming.length?<div className="grid">{upcoming.map(a=><AnimeCard key={a.routeId||a.id} anime={a}/>)}</div>:<div className="empty">No upcoming anime available right now.</div>}</section>
  <section id="how" className="info"><div><span className="kicker">ABOUT THE DATA</span><h2>Real anime data, not placeholders.</h2><p>AniPulse uses multiple public anime databases. AniList is the primary source, with Jikan / MyAnimeList and Kitsu available as fallbacks. Each anime also has its own overview page with a longer synopsis and detailed release information.</p></div><div className="sourceBox"><span>ACTIVE DATA SOURCE</span><b>{source || 'Connecting…'}</b><small>Public APIs · No API key required</small>{updated&&<small>Last synced · {new Date(updated).toLocaleTimeString()}</small>}</div></section>
  <footer><div className="brand"><span className="logo"><Sparkles size={16}/></span><b>AniPulse</b></div><span>AniList · Jikan / MyAnimeList · Kitsu</span></footer>
 </main>
}
