'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ChevronRight, Flame, Sparkles, AlertCircle, Menu, X } from 'lucide-react';
import AnimeCard, { Anime } from '../components/AnimeCard';
import AnimeSearch from '../components/AnimeSearch';
import AuthNav from '../components/AuthNav';

export default function Home(){
 const [latest,setLatest]=useState<Anime[]>([]),[upcoming,setUpcoming]=useState<Anime[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updated,setUpdated]=useState(''),[source,setSource]=useState('');
 const [menuOpen,setMenuOpen]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/anime?section=latest&page=1&limit=8',{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error);setLatest(data.data||[]);const u=await fetch('/api/anime?section=upcoming&page=1&limit=8',{cache:'no-store'});const upcomingData=await u.json();setUpcoming(upcomingData.data||[]);setUpdated(data.updatedAt||'');setSource(data.source||'Anime databases')}catch(e){setError(e instanceof Error?e.message:'Unable to load anime data.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const total=latest.length+upcoming.length;
 const closeMenu=()=>setMenuOpen(false);
 return <main>
  <nav className="siteNav"><Link className="brand" href="/" onClick={closeMenu}><span className="logo"><Sparkles size={18}/></span><b>AniPulse</b></Link><div className="navlinks"><Link href="/" className="active">Home</Link><Link href="/latest">Latest</Link><Link href="/upcoming">Upcoming</Link><Link href="#how" onClick={closeMenu}>About</Link></div><div className="desktopSearch"><AnimeSearch /></div><AuthNav /><button className={`mobileMenuButton${menuOpen?' isOpen':''}`} aria-label={menuOpen?'Close navigation':'Open navigation'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X size={21}/>:<Menu size={21}/>}</button>{menuOpen&&<div className="mobileNav"><div className="mobileNavHeader"><span><Sparkles size={14}/> MENU</span><small>ANIPULSE</small></div><div className="mobileSearch"><AnimeSearch compact /></div><Link href="/" onClick={closeMenu}><span>Home</span><ChevronRight size={15}/></Link><Link href="/latest" onClick={closeMenu}><span>Latest anime</span><ChevronRight size={15}/></Link><Link href="/upcoming" onClick={closeMenu}><span>Upcoming releases</span><ChevronRight size={15}/></Link><Link href="#how" onClick={closeMenu}><span>About</span><ChevronRight size={15}/></Link><div className="mobileAuth"><AuthNav /></div></div>}</nav>
  <section id="top" className="hero"><div className="heroGlow"/><div className="heroCopy"><div className="eyebrow"><Flame size={14}/> LIVE ANIME RADAR</div><h1>Your next<br/><em>favorite anime.</em></h1><p>Discover what is airing now and what is coming next, with real titles, artwork, release dates and synopses pulled from public anime databases.</p><div className="heroActions"><Link className="primary" href="/latest">Explore latest <ChevronRight size={17}/></Link><span><span className="liveDot"/> {source || 'Connecting to anime databases…'}</span></div></div><div className="heroPanel"><div className="panelTop"><span>DATABASE STATUS</span><span className="online"><i/> {loading?'SYNCING':'ONLINE'}</span></div><div className="bigNumber">{total || (loading?'…':'0')}</div><p>anime currently surfaced across this season and the upcoming slate.</p><div className="miniStats"><div><b>{latest.length}</b><span>airing now</span></div><div><b>{upcoming.length}</b><span>coming soon</span></div></div></div></section>
  <section id="latest" className="section"><div className="sectionHead"><div><span className="kicker">ON AIR NOW</span><h2>Latest anime</h2><p>Highlights from the current season.</p></div><Link className="textLink" href="/latest">View all <ChevronRight size={16}/></Link></div>{error&&<div className="error"><AlertCircle size={18}/><span>{error}</span><button onClick={load}>Try again</button></div>}{loading?<div className="skeletonGrid">{Array.from({length:8}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:latest.length?<div className="grid">{latest.map(a=><AnimeCard key={a.routeId||a.id} anime={a}/>)}</div>:<div className="empty">No latest anime available right now.</div>}</section>
  <section id="upcoming" className="section upcoming"><div className="sectionHead"><div><span className="kicker">COMING SOON</span><h2>Upcoming releases</h2><p>Future anime with announced release dates.</p></div><Link className="textLink" href="/upcoming">Browse all <ChevronRight size={16}/></Link></div>{loading?<div className="skeletonGrid">{Array.from({length:8}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:upcoming.length?<div className="grid">{upcoming.map(a=><AnimeCard key={a.routeId||a.id} anime={a}/>)}</div>:<div className="empty">No upcoming anime available right now.</div>}</section>
  <section id="how" className="info"><div><span className="kicker">ABOUT THE DATA</span><h2>Real anime data, not placeholders.</h2><p>AniPulse uses multiple public anime databases. AniList is the primary source, with Jikan / MyAnimeList and Kitsu available as fallbacks. Each anime also has its own overview page with a longer synopsis and detailed release information.</p></div><div className="sourceBox"><span>ACTIVE DATA SOURCE</span><b>{source || 'Connecting…'}</b><small>Public APIs · No API key required</small>{updated&&<small>Last synced · {new Date(updated).toLocaleTimeString()}</small>}</div></section>
  <footer><div className="brand"><span className="logo"><Sparkles size={16}/></span><b>AniPulse</b></div><span>AniList · Jikan / MyAnimeList · Kitsu</span></footer>
  <style jsx global>{`@media (max-width:800px){.siteNav>.desktopSearch{display:none}.siteNav>.authNavButton{display:none}.mobileMenuButton{display:flex;flex-shrink:0;align-items:center;justify-content:center;width:42px;height:42px;padding:0;border:1px solid #b8ff6438;border-radius:12px;background:linear-gradient(145deg,#151a19,#0d1112);color:#b8ff64;box-shadow:0 0 0 1px #ffffff08 inset,0 8px 24px #0008,0 0 18px #b8ff6408;transition:transform .2s ease,box-shadow .2s ease,border-color .2s ease,background .2s ease}.mobileMenuButton:hover{border-color:#b8ff6470;background:#172016;box-shadow:0 0 22px #b8ff6418,0 8px 24px #0008}.mobileMenuButton:active{transform:scale(.93)}.mobileMenuButton.isOpen{background:#b8ff64;color:#081008;border-color:#b8ff64;box-shadow:0 0 25px #b8ff6430,0 8px 24px #0008}.mobileNav{position:absolute;display:flex;flex-direction:column;gap:5px;top:76px;left:4vw;right:4vw;padding:12px;background:linear-gradient(145deg,#11151cfa,#090c11fa);border:1px solid #ffffff12;border-radius:0 0 18px 18px;box-shadow:0 25px 60px #000c,0 0 35px #b8ff640a;backdrop-filter:blur(22px);z-index:250;overflow:hidden}.mobileNav:before{content:'';position:absolute;top:0;left:20px;right:20px;height:2px;background:linear-gradient(90deg,transparent,#b8ff64,transparent);opacity:.75}.mobileNavHeader{display:flex;justify-content:space-between;align-items:center;padding:7px 10px 10px;color:#b8ff64;font-size:10px;letter-spacing:1.5px}.mobileNavHeader span{display:flex;align-items:center;gap:6px;font-weight:700}.mobileNavHeader small{color:#5e626c;font-size:8px;letter-spacing:2px}.mobileNav .mobileSearch{display:block;padding:2px 2px 8px}.mobileNav .mobileSearch .search{width:100%!important;background:#070a0d;border-color:#ffffff14;box-shadow:0 5px 18px #0006}.mobileNav>a{display:flex;align-items:center;justify-content:space-between;padding:13px 13px;border:1px solid transparent;border-radius:10px;color:#bfc1c9;font-size:13px;transition:.18s}.mobileNav>a svg{color:#5e636d;transition:.18s}.mobileNav>a:hover{background:#b8ff640b;border-color:#b8ff6415;color:#b8ff64}.mobileNav>a:hover svg{color:#b8ff64;transform:translateX(2px)}.mobileAuth{padding-top:5px;border-top:1px solid #ffffff0b}.mobileNav .authNavButton{display:block;width:100%;margin-top:7px;text-align:center;background:#ffffff08;border-color:#ffffff14}.siteNav{gap:10px}.hero{padding-top:60px}}@media(min-width:801px){.mobileSearch,.mobileNav{display:none}}`}</style>
 </main>
}
